apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ui
    version: v1
  name: ui
spec:
  selector:
    matchLabels:
      app: ui
      version: v1
  template:
    metadata:
      labels:
        app: ui
        version: v1
    spec:
      containers:
      - image: default-route-openshift-image-registry.apps-crc.testing/tekton-argocd/tutorial-tekton-argocd-code
        imagePullPolicy: Always
        name: ui
        ports:
        - containerPort: 3000
